title: Rapport sur Yuka

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

collections:
  docs:
    permalink: "/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Rapport
      nav_fold: true

